# Generated by Django 4.0.6 on 2022-07-11 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(choices=[('CEO', 'Ceo'), ('DIR', 'Director'), ('MGR', 'Manager'), ('TML', 'Teamlead'), ('DVP', 'Developer')], default='DVP', max_length=3)),
                ('hired', models.DateField(default=django.utils.timezone.now)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employer')),
            ],
        ),
    ]
