# Generated by Django 4.0.6 on 2022-07-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employer_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
